### ISSUE TITLE
New version with dark background

### ISSUE THREAD

**Issue by JoseCage** [tsbarnes/numix-ui#1]
Hello. I recently installed the theme on my atom and happens to be interesting. But it seems just have light background, what bothers his eyes a little.

It will be possible in future also release a version with dark background?

Thank you.

**Comment by tsbarnes** [comment]
I'm planning on it, though I'm not sure how long it will be until I get time to work on it.

**Comment by JoseCage** [comment]
Allright @tsbarnes I hope you have time to do such a version and launch it.
I'll be waiting for the release...
